name: mamopay_test
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  iod: ^0.0.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  uuid: ^4.4.0
  firebase_core: ^2.27.1
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.17.9
  cached_network_image: 3.4.0
  flutter_carousel_widget: ^3.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mocktail: ^1.0.0
  bloc_test: ^9.1.4
  fake_cloud_firestore: ^2.5.2

flutter:
  uses-material-design: true


